.TH EE 8 "v\ 1.0" "Thu, September 26, 2013" "EasyEngine"
.SH NAME
.B ee
\- Manage Nginx Based Websites.
.SH SYNOPSIS
ee help
.TP
ee site [ create | delete | disable | enable | list | listall | show ]
.TP
ee system [ info| install | remove | purge ]
.br
.SH DESCRIPTION
EasyEngine (EE) is a shell script to help site administrators manage nginx-based websites.
.br
.SH OPTIONS
.TP
.B create
.br
Create HTML, PHP and WordPress Websites
.TP
.B delete
.br
Delete HTML, PHP and WordPress Websites
.TP
.B disable
.br
Disable Website
.TP
.B enable
.br
Enable Website
.TP
.B list
.br
List Enabled Websites
.TP
.B listall
.br
List All Websites
.TP
.B show
.br
Show Nginx Configuration For Website
.TP
.B info
.br
Information About Nginx And PHP
.TP
.B install
.br
Install Nginx PHP5 MySQL Postfix System Packages
.TP
.B remove
.br
Remove Nginx PHP5 MySQL Postfix System Packages
.TP
.B purge
.br
Purge Nginx PHP5 MySQL Postfix System Packages
.SH EXAMPLES
.br
Please visit: http://rtcamp.com/easyengine/docs/
.P
.SH VERSION
.B ee (EasyEngine)
version 1.0
.SH "SEE ALSO"
.br
.TP
EE: 
.I   http://rtcamp.com/easyengine
.br
.TP
FAQ: 
.I  http://rtcamp.com/easyengine/faq/
.br
.TP
DOCS:
.I http://rtcamp.com/easyengine/docs/
.SH AUTHOR
.br
.B rtCamp Team 
.I \<admin@rtcamp.com\>
.br
.B Mitesh Shah 
.I \<Mitesh.Shah@rtcamp.com\>
.br
.B Manish 
.I \<Manish.Songirkar@rtcamp.com\>