#!/bin/bash

# Make Variables Available For Later Use
LOGDIR=/var/log/easyengine
ERRORLOG=/var/log/easyengine/error.log
INSTALLLOG=/var/log/easyengine/install.log
LINUX_DISTRO=$(lsb_release -i | cut -d':' -f2 | awk '{print $1}')

# Main EasyEngine Function To Log All The Outputs
EasyEngine()
{

# Add TimeStamps In Install Log File
echo &>> $INSTALLLOG
echo &>> $INSTALLLOG
echo -e "\033[34mEasyEngine (ee) Execution Started [$(date)]\e[0m" &>> $INSTALLLOG
echo -e "\033[34mEasyEngine (ee) Command: $0 $@\e[0m" &>> $INSTALLLOG


# Capture Errors
OwnError()
{
	echo -e "[ `date` ] \033[31m $@ \e[0m" | tee -ai $ERRORLOG
	exit 101
}

# Check Auto Assume Yes Or No To Apt-Get
APTASSUMEYES ()
{
	grep apt-get-assume-yes /etc/easyengine/ee.conf | grep -i true &>> /dev/null
	if [ $? -eq 0 ]
	then
		EEAPTGET="apt-get -y"
	else
		# Check Any WebServer Package Is Installed Or Not
		dpkg -l | egrep -e 'nginx|php|mysql|postfix|apache' &>> $INSTALLLOG
		if [ $? -ne 0 ]
		then
			EEAPTGET="apt-get -y"
		else
			EEAPTGET="apt-get"
		fi
	fi
}

# Install Package Functions
PYTHONSOFTWARE()
{
	# Install Python Software Properties
	echo -e "\033[34mInstalling Python Software Properties, Please Wait...\e[0m"
	$EEAPTGET install python-software-properties \
	|| OwnError "Unable To Install Python Software Properties"
}

NGINXREPO()
{
	if [ "$LINUX_DISTRO" == "Ubuntu" ]
	then
		# Add Nginx Launchpad Repository
		echo -e "\033[34mAdding Brianmercer Nginx Launchpad Repository, Please Wait...\e[0m"
		add-apt-repository -y ppa:brianmercer/nginx &>> $INSTALLLOG \
		|| OwnError "Unable To Add Nginx Launchpad Repository"

	elif [ "$LINUX_DISTRO" == "Debian" ]
	then
		# Add Nginx DotDeb Repository
		echo -e "\033[34mAdding Nginx DotDeb Repository, Please Wait...\e[0m"
		echo "deb http://packages.dotdeb.org $(lsb_release -c | awk '{print($2)}') all" > /etc/apt/sources.list.d/dotdeb-$(lsb_release -c | awk '{print($2)}').list \
		|| OwnError "Unable To Add Nginx DotDeb Repository"

		# Fetch And Install The GnuPG Key
		wget -qcO /tmp/dotdeb.gpg http://www.dotdeb.org/dotdeb.gpg || OwnError "Unable To Download DotDeb GnuPG Key"
		apt-key add /tmp/dotdeb.gpg &>> $INSTALLLOG || OwnError "Unable To Add DotDeb GnuPG Key"
	fi
}

PHPREPO()
{
	if [ "$LINUX_DISTRO" == "Ubuntu" ]
	then
		# Add PHP Launchpad Repository
		echo -e "\033[34mAdding Ondrej PHP5 Launchpad Repository, Please Wait...\e[0m"
		add-apt-repository -y ppa:ondrej/php5 &>> $INSTALLLOG \
		|| OwnError "Unable To Add PHP5 Launchpad Repository"

	elif [ "$LINUX_DISTRO" == "Debian" ]
	then
		# Detect Debian Version To Select PHP Repo
		DEBIAN_VERSION=$(lsb_release -r | awk '{print($2)}' | cut -d'.' -f1)

		if [ $DEBIAN_VERSION -eq 6 ]
		then
			# Add PHP DotDeb Repository
			echo -e "\033[34mAdding PHP5.4 DotDeb Repository, Please Wait...\e[0m"
			echo "deb http://packages.dotdeb.org $(lsb_release -c | awk '{print($2)}')-php54 all" > /etc/apt/sources.list.d/dotdeb-$(lsb_release -c | awk '{print($2)}')-php54.list \
			|| OwnError "Unable To Add PHP5.4 DotDeb Repository"

		elif [ $DEBIAN_VERSION -eq 7 ]
		then
			# Add PHP DotDeb Repository
			echo -e "\033[34mAdding PHP5.5 DotDeb Repository, Please Wait...\e[0m"
			echo "deb http://packages.dotdeb.org $(lsb_release -c | awk '{print($2)}')-php55 all" > /etc/apt/sources.list.d/dotdeb-$(lsb_release -c | awk '{print($2)}')-php55.list \
			|| OwnError "Unable To Add PHP5.5 DotDeb Repository"
		fi
		
		# Fetch And Install The GnuPG Key
		wget -qcO /tmp/dotdeb.gpg http://www.dotdeb.org/dotdeb.gpg || OwnError "Unable To Download DotDeb GnuPG Key"
		apt-key add /tmp/dotdeb.gpg &>> $INSTALLLOG || OwnError "Unable To Add DotDeb GnuPG Key"
	fi
}

GPGKEY()
{
	# Force GPG KEYS Check
	grep gpg-keys-fix /etc/easyengine/ee.conf | grep -i true &>> /dev/null

	if [ $? -eq 0 ]
	then
		# Fix GPG Key Problems
		echo -e "\033[34mChecking GPG Keys For Brianmercer Nginx Repository, Please Wait...\e[0m"
		apt-get update > /dev/null 2> /tmp/keymissing \
		|| OwnError "Unable To Fix GPG Keys For Brianmercer Nginx Repository "

		for key in $(grep "NO_PUBKEY" /tmp/keymissing |sed "s/.*NO_PUBKEY //")
		do
			echo -e "\033[34mProcessing key: $key\e[0m"
			gpg --keyserver subkeys.pgp.net --recv $key && gpg --export --armor $key | apt-key add -
		done
	fi
}

UPDATEAPT()
{
	# Update The APT Cache
	echo -e "\033[34mUpdating APT Cache, Please Wait...\e[0m"
	apt-get update &>> $INSTALLLOG || OwnError "Unable To Update APT Cache"
}

INSTALLNGINX()
{
	# Install Nginx
	echo -e "\033[34mInstalling Nginx, Please Wait...\e[0m"
	$EEAPTGET install $NGINXPACKAGE || OwnError "Unable To Install Nginx"
}

EEMD5SUM()
{
	SOURCE=$EESOURCE
	DEST=$EEDEST

	for i in $SOURCE/*
	do
        # Get File Name
        EEFILE=$(basename $i)

        SOURCEMD5SUM=$(md5sum $SOURCE/$EEFILE | cut -d' ' -f1)
        DESTMD5SUM=$(md5sum $DEST/$EEFILE 2> /dev/null | cut -d' ' -f1)

        # Check If Destination File Exist
        if [ -z "$DESTMD5SUM" ]
        then
                # Copy Missing Destination Files
                cp -i $SOURCE/$EEFILE $DEST/$EEFILE

        elif [ "$SOURCEMD5SUM" != "$DESTMD5SUM" ]
        then
                # Update Destination On MD5SUM Not Matched
                cp -i $SOURCE/$EEFILE $DEST/$EEFILE
        fi  
	done
}

HTTPAUTH()
{
	# Get The htpasswd Details
	HTPASSWDUSER=$(grep htpasswduser /etc/easyengine/ee.conf | awk '{print($3)}')
	HTPASSWDPASS=$(grep htpasswdpass /etc/easyengine/ee.conf | awk '{print($3)}')

	# Ask User To Provide HTTP AUTH Username & Password
	if [ -z "$HTPASSWDUSER" ]
	then
		read -p "Enter The HTTP AUTH Username [easyengine]: " HTPASSWDUSER
		# Turn Off Echo For Passwords
		stty -echo
		read -p "Enter The HTTP AUTH Password [easyengine]: " HTPASSWDPASS
		stty echo
		echo
	fi

	# If Enter Is Pressed, User Defaults
	if [[ $HTPASSWDUSER = "" ]]
	then
		HTPASSWDUSER=easyengine
	fi

	if [[ $HTPASSWDPASS = "" ]]
	then
		HTPASSWDPASS=easyengine
	fi

	# Add HTTP Auth Details In EE Configuration File
	sed -i "s/htpasswduser.*/htpasswduser = $HTPASSWDUSER/" /etc/easyengine/ee.conf
	sed -i "s/htpasswdpass.*/htpasswdpass = $HTPASSWDPASS/" /etc/easyengine/ee.conf

	# Generate htpasswd-ee file
	printf "$HTPASSWDUSER:$(openssl passwd -crypt $HTPASSWDPASS 2> /dev/null)\n" > /etc/nginx/htpasswd-ee 2> /dev/null
}

COMMONNGINX()
{
	# Personal Settings For Nginx
	echo -e "\033[34mUpdating Nginx Configuration Files, Please Wait...\e[0m"

	grep "Easy Engine" /etc/nginx/nginx.conf &> /dev/null
	if [ $? -ne 0 ]
	then

		# Change Nginx Main Section Settings	
		sed -i "s/worker_processes.*/worker_processes auto;/" /etc/nginx/nginx.conf
		sed -i "/worker_processes/a \worker_rlimit_nofile 100000;" /etc/nginx/nginx.conf

		# Change Nginx Events Section Settings
		sed -i "s/worker_connections.*/worker_connections 1024;/" /etc/nginx/nginx.conf
		sed -i "s/# multi_accept/multi_accept/" /etc/nginx/nginx.conf

		# Disable Nginx Version Set Custom Headers Proxy And SSL Settings
		sed -i "s/http {/http {\n\t##\n\t# Easy Engine Settings\n\t##\n\n\tserver_tokens off;\n\treset_timedout_connection on;\n\tadd_header X-Powered-By "EasyEngine";\n\tadd_header rt-Fastcgi-Cache \$upstream_cache_status;\n\n\t# Limit Request\n\tlimit_req_status 403;\n\tlimit_req_zone \$binary_remote_addr zone=one:10m rate=1r\/s;\n\n\t# Proxy Settings\n\t# set_real_ip_from\tproxy-server-ip;\n\t# real_ip_header\tX-Forwarded-For;\n\n\tfastcgi_read_timeout 300;\n\tclient_max_body_size 100m;\n\n\t# SSL Settings\n\tssl_session_cache shared:SSL:20m;\n\tssl_session_timeout 10m;\n\tssl_prefer_server_ciphers on;\n\tssl_ciphers HIGH:\!aNULL:\!MD5:\!kEDH;\n\n/" /etc/nginx/nginx.conf

		# Change Keepalive Timeout Settings
		sed -i "s/keepalive_timeout.*/keepalive_timeout 30;/" /etc/nginx/nginx.conf

		# Set Custom Logs
		sed -i "s/error_log.*/error_log \/var\/log\/nginx\/error.log;\n\n\tlog_format rt_cache '\$remote_addr \$upstream_response_time \$upstream_cache_status [\$time_local] '\n\t\t'\$http_host \"\$request\" \$status \$body_bytes_sent '\n\t\t'\"\$http_referer\" \"\$http_user_agent\"';/" /etc/nginx/nginx.conf

		# Enable Gzip
		sed -i "s/# gzip/gzip/" /etc/nginx/nginx.conf
	fi

	# Check Directory Exist
	if [ ! -d /etc/nginx/conf.d ]
	then
		mkdir /etc/nginx/conf.d || OwnError "Unable To Create /etc/nginx/conf.d"
	fi

	if [ ! -d /etc/nginx/common ]
	then
		mkdir /etc/nginx/common || OwnError "Unable To Create /etc/nginx/common"
	fi

	# Update Nginx Configuration Files
	EESOURCE="/usr/share/easyengine/nginx/conf.d"
	EEDEST="/etc/nginx/conf.d"
	EEMD5SUM

	# Update Nginx Common Files
	EESOURCE="/usr/share/easyengine/nginx/common"
	EEDEST="/etc/nginx/common"
	EEMD5SUM

	# White List IP Address
	echo -e "\033[34mEasyEngine (ee) Allow To Access Protected Files By Using Whitelisted IP Address Or HTTP Authentication\e[0m"
	stty echo
	read -p "Enter The IP Address To Whitelist: " WHITELISTIP
	if [[ $WHITELISTIP != "" ]]
	then
			sed -i "s/deny.*/$(echo "allow $WHITELISTIP;")\ndeny all;/" /etc/nginx/common/acl.conf
	fi

	# Protect EE Locations
	HTTPAUTH
}

INSTALLPHP()
{
	# Install PHP5
	echo -e "\033[34mInstalling PHP5, Please Wait...\e[0m"
	$EEAPTGET install php5-common php5-mysqlnd php5-xmlrpc \
	php5-curl php5-gd php5-cli php5-fpm php5-imap php5-mcrypt \
	php5-memcache memcached  || OwnError "Unable To Install PHP5"
}

COMMONPHP()
{
	# Personal Settings For PHP
	echo -e "\033[34mUpdating PHP Configuration Files, Please Wait...\e[0m"

	grep "Easy Engine" /etc/php5/fpm/php.ini &> /dev/null
	if [ $? -ne 0 ]
	then

		# Move PHP’s Session Storage To Memcache
		sed -i "/extension/a \session.save_handler = memcache\nsession.save_path = \"tcp://localhost:11211\"" /etc/php5/mods-available/memcache.ini

		# Change PHP Settings
		sed -i "s/\[PHP\]/[PHP]\n; Easy Engine/" /etc/php5/fpm/php.ini
		sed -i "s/expose_php.*/expose_php = Off/" /etc/php5/fpm/php.ini
		sed -i "s/post_max_size.*/post_max_size = 100M/" /etc/php5/fpm/php.ini
		sed -i "s/upload_max_filesize.*/upload_max_filesize = 100M/" /etc/php5/fpm/php.ini
		sed -i "s/max_execution_time.*/max_execution_time = 300/" /etc/php5/fpm/php.ini

		# Enable PHP Status & Ping
		sed -i "s/;ping.path/ping.path/" /etc/php5/fpm/pool.d/www.conf
		sed -i "s/;pm.status_path/pm.status_path/" /etc/php5/fpm/pool.d/www.conf

		# Change PHP Pool Settings MAX Servers & Request Terminate Timeout
		sed -i "s/;pm.max_requests/pm.max_requests/" /etc/php5/fpm/pool.d/www.conf
		sed -i "s/pm.max_children = 5/pm.max_children = 100/" /etc/php5/fpm/pool.d/www.conf
		sed -i "s/pm.start_servers = 2/pm.start_servers = 20/" /etc/php5/fpm/pool.d/www.conf
		sed -i "s/pm.min_spare_servers = 1/pm.min_spare_servers = 10/" /etc/php5/fpm/pool.d/www.conf
		sed -i "s/pm.max_spare_servers = 3/pm.max_spare_servers = 30/" /etc/php5/fpm/pool.d/www.conf
		sed -i "s/;request_terminate_timeout.*/request_terminate_timeout = 300/" /etc/php5/fpm/pool.d/www.conf
		
		# Change PHP Fastcgi Socket
		sed -i "s'listen = /var/run/php5-fpm.sock'listen = 127.0.0.1:9000'" /etc/php5/fpm/pool.d/www.conf || OwnError "Unable To Change PHP Fastcgi Socket"
	fi
}

WP-CLI()
{
	# Install WP-CLI
	if [ ! -d /usr/share/easyengine/wp-cli ]
	then
		echo -e "\033[31mWP-CLI Command Not Found\e[0m"
		echo -e "\033[34mInstalling WP-CLI, Please Wait...\e[0m"
		curl -sL https://raw.github.com/wp-cli/wp-cli.github.com/master/installer.sh | INSTALL_DIR='/usr/share/easyengine/wp-cli' VERSION='0.14.1' bash &>> $INSTALLLOG \
		|| OwnError "Unable To Install WP-CLI"

		# Add WP-CLI Command In PATH Variable
		ln -s /usr/share/easyengine/wp-cli/bin/wp /usr/bin/wp || OwnError "Unable To Create Symbolic Link For WP-CLI Command"

		# Add WP-CLI Auto Completion
		cp -i /usr/share/easyengine/wp-cli/vendor/wp-cli/wp-cli/utils/wp-completion.bash /etc/bash_completion.d/
		source /etc/bash_completion.d/wp-completion.bash
	else
		echo -e "\033[34mAlready Installed WP-CLI (/usr/share/easyengine/wp-cli)...\e[0m"
	fi
}

INSTALLPMA()
{
	# Install PMA/phpMyAdmin
	if [ ! -d /var/www/eeadmin/htdocs/db ]
	then
		if [ ! -d /var/www/eeadmin/htdocs/db/pma ]
		then
			echo -e "\033[34mDownloading phpMyAdmin, Please Wait...\e[0m"

			# Setup PMA/phpMyAdmin
			mkdir -p /var/www/eeadmin/htdocs/db/pma/ || OwnError "Unable To Create phpMyAdmin Directory: /var/www/eeadmin/htdocs/db/pma/"

			# Download PMA/phpMyAdmin
			wget -cqO /var/www/eeadmin/htdocs/db/pma/pma.tar.gz http://dl.cihar.com/phpMyAdmin/master/phpMyAdmin-master-latest.tar.gz \
			|| OwnError "Unable To Download phpMyAdmin"

			# Extract PMA/phpMyAdmin
			tar --strip-components=1 -zxf  /var/www/eeadmin/htdocs/db/pma/pma.tar.gz -C /var/www/eeadmin/htdocs/db/pma/ \
			|| OwnError "Unable To Extract phpMyAdmin"

			# Remove Unwanted Files
			rm -f /var/www/eeadmin/htdocs/db/pma/pma.tar.gz

		fi
	
		if [ ! -d /var/www/eeadmin/htdocs/db/adminer ]
		then
			echo -e "\033[34mDownloading Adminer, Please Wait...\e[0m"
			# Setup Adminer
			mkdir -p /var/www/eeadmin/htdocs/db/adminer/ || OwnError "Unable To Create Adminer Directory: /var/www/eeadmin/htdocs/db/adminer/"

			# Download Adminer
			wget -cqO /var/www/eeadmin/htdocs/db/adminer/index.php http://downloads.sourceforge.net/adminer/adminer-4.0.3.php \
			|| OwnError "Unable To Download Adminer"

		fi

	else
		echo -e "\033[34mAlready Installed phpMyAdmin (/var/www/eeadmin/htdocs/db/pma)...\e[0m"
	fi
}

MYSQLINSTALLTWEAKS()
{
	# MySQL Password Only Set If MySQL Is Not Installed
	# If MySQL Is Installed Don't Set Wrong Password In ~/.my.cnf
	dpkg -l | grep mysql-server &>> $INSTALLLOG

	if [ $? -ne 0 ]
	then
		# Setting Up MySQL Password
		MYSQLAUTOPASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n1)
		debconf-set-selections <<< "mysql-server mysql-server/root_password password $MYSQLAUTOPASS"
		debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $MYSQLAUTOPASS"

		# Generate ~/.my.cnf
		echo -e "[client]\nuser=root\npassword=$MYSQLAUTOPASS" > ~/.my.cnf
	fi
}

INSTALLMYSQL()
{
	# Setting Up MySQL Password
	MYSQLINSTALLTWEAKS

	# Install MySQL
	echo -e "\033[34mInstalling MySQL, Please Wait...\e[0m"
	$EEAPTGET install mysql-server mysqltuner \
	|| OwnError "Unable To Install MySQL"
}

POSTFIXINSTALLTWEAKS()
{
	# Setting Up Postfix
	debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
	debconf-set-selections <<< "postfix postfix/mailname string $(hostname -f)"
}

INSTALLPOSTFIX()
{
	# Setting Up Postfix
	POSTFIXINSTALLTWEAKS

	# Install Postfix
	echo -e "\033[34mInstalling Postfix, Please Wait...\e[0m"
	$EEAPTGET install postfix || OwnError "Unable To Install Postfix"
}

INSTALLALL()
{
	# Setting Up MySQL & Postfix
	MYSQLINSTALLTWEAKS
	POSTFIXINSTALLTWEAKS

	# Install Nginx PHP5 MySQL Postfix
	echo -e "\033[34mInstalling Nginx PHP5 MySQL Postfix, Please Wait...\e[0m"
	$EEAPTGET install $NGINXPACKAGE php5-common php5-mysqlnd php5-xmlrpc \
	php5-curl php5-gd php5-cli php5-fpm php5-imap php5-mcrypt \
	php5-memcache memcached mysql-server mysqltuner postfix \
	|| OwnError "Unable To Install Nginx PHP5 MySQL Postfix"
}


# Remove Package Functions
REMOVENGINX()
{
	# Remove Nginx
	echo -e "\033[34mRemoving Nginx, Please Wait...\e[0m"
	$EEAPTGET remove $NGINXPACKAGE nginx-common || OwnError "Unable To Remove Nginx"
}

REMOVEPHP()
{
	# Remove PHP5
	echo -e "\033[34mRemoving PHP5, Please Wait...\e[0m"
	$EEAPTGET remove php5-common php5-mysqlnd php5-xmlrpc \
	php5-curl php5-gd php5-cli php5-fpm php5-imap php5-mcrypt \
	php5-memcache memcached || OwnError "Unable To Remove PHP5"
}

REMOVEWPCLI()
{
	# Remove WP-CLI
	echo -e "\033[34mRemoving WP-CLI, Please Wait...\e[0m"
	rm -rf /usr/share/easyengine/wp-cli /usr/bin/wp /etc/bash_completion.d/wp-completion.bash || OwnError "Unable To Remove WP-CLI"
}

REMOVEPMA()
{
	# Remove PMA/phpMyAdmin
	echo -e "\033[34mRemoving phpMyAdmin, Please Wait...\e[0m"
	rm -rf /var/www/eeadmin/htdocs/db/pma || OwnError "Unable To Remove phpMyAdmin"
}

REMOVEMYSQL()
{
	# Remove MySQL
	echo -e "\033[34mRemoving MySQL, Please Wait...\e[0m"
	$EEAPTGET remove mysql-server mysqltuner \
	|| OwnError "Unable To Remove MySQL"
}

REMOVEPOSTFIX()
{
	# Remove Postfix
	echo -e "\033[34mRemoving Postfix, Please Wait...\e[0m"
	$EEAPTGET remove postfix || OwnError "Unable To Remove Postfix"
}

REMOVEALL()
{
	# Remove Nginx PHP5 MySQL Postfix
	echo -e "\033[34mRemoving Nginx PHP5 MySQL Postfix, Please Wait...\e[0m"
	$EEAPTGET remove $NGINXPACKAGE nginx-common php5-common php5-mysqlnd php5-xmlrpc \
	php5-curl php5-gd php5-cli php5-fpm php5-imap php5-mcrypt \
	php5-memcache memcached mysql-server mysqltuner postfix \
	|| OwnError "Unable To Remove Nginx PHP5 MySQL Postfix"
}

AUTOREMOVE()
{
	# Remove Unwanted Packages
	echo -e "\033[34mRemoving Unwanted Packages, Please Wait...\e[0m"
	$EEAPTGET autoremove || OwnError "Unable To Auto Remove"
}


# Purge Package Functions
PURGENGINX()
{
	# Purge Nginx
	echo -e "\033[34mPurge Nginx, Please Wait...\e[0m"
	$EEAPTGET purge $NGINXPACKAGE nginx-common || OwnError "Unable To Purge Nginx"
}

PURGEPHP()
{
	# Purge PHP5
	echo -e "\033[34mPurge PHP5, Please Wait...\e[0m"
	$EEAPTGET purge php5-common php5-mysqlnd php5-xmlrpc \
	php5-curl php5-gd php5-cli php5-fpm php5-imap php5-mcrypt \
	php5-memcache memcached || OwnError "Unable To Purge PHP5"
}

PURGEMYSQL()
{
	# Purge MySQL
	echo -e "\033[34mPurge MySQL, Please Wait...\e[0m"
	$EEAPTGET purge mysql-server mysqltuner \
	|| OwnError "Unable To Purge MySQL"
}

PURGEPOSTFIX()
{
	# Purge Postfix
	echo -e "\033[34mPurge Postfix, Please Wait...\e[0m"
	$EEAPTGET purge postfix || OwnError "Unable To Purge Postfix"
}

PURGEALL()
{
	# Purge Nginx PHP5 MySQL Postfix
	echo -e "\033[34mRemoving Nginx PHP5 MySQL Postfix, Please Wait...\e[0m"
	$EEAPTGET purge $NGINXPACKAGE nginx-common php5-common php5-mysqlnd php5-xmlrpc \
	php5-curl php5-gd php5-cli php5-fpm php5-imap php5-mcrypt \
	php5-memcache memcached mysql-server mysqltuner postfix \
	|| OwnError "Unable To Purge Nginx PHP5 MySQL Postfix"
}


# EE GIT Function
EEGITINIT()
{
	# Change Directory
	cd $EEGITDIR || OwnError "Unable To Change Directory $EEGITDIR"

	# Check .git
	if [ ! -d .git ]
	then
		# Initialise Git
		echo -e "\033[34mInitialise Git On $EEGITDIR...\e[0m"
		git init &>> $INSTALLLOG || OwnError "Unable To Initialize Git On $EEGITDIR"
	fi

	# Check For Untracked Files
	git status | grep clean
	if [ $? -ne 0 ]
	then
		# Add Files In Git Version Control
		git add --all && git commit -am "Initialize Git On $EEGITDIR"  &>> $INSTALLLOG \
		|| OwnError "Unable To Git Commit On $EEGITDIR"
	fi
}

EEGITCOMMIT()
{
	cd $EEGITDIR || OwnError "Unable To Change Directory $EEGITDIR"
	git status | grep --color=auto clean

	if [ $? -ne 0 ]
	then
		# Git Commit Functionality
		echo -e "\033[34mTake $EEGITDIR Configuration In Git Version Control...\e[0m"

		# Add Newly Created Files && Commit It
		git add --all && git commit -am "$EEGITMESSAGE" &>> $INSTALLLOG \
		|| OwnError "Unable To Git Commits On $EEGITDIR"
	fi
}

MYSQLUSERPASS()
{
	read -p "Enter The MySQL Username [root]: " MYSQLUSER
	# If Enter Is Pressed, Then Use root as MySQL User
	if [[ $MYSQLUSER = "" ]]
	then
		MYSQLUSER=root
	fi

	# Turn Off Echo For Passwords
	stty -echo
	read -p "Enter The MySQL Password: " MYSQLPASS
	stty echo
	echo
}


MYSQLPASSCHECK()
{
	while [ -n $(mysqladmin -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASS ping 2> /dev/null | grep alive) &> /dev/null ]
	do
		# Verify MySQL Credentials
		MYSQLUSERPASS
	done
}

MYSQLROOT()
{
	MYSQLUSER=$(cat ~/.my.cnf | grep user | cut -d'=' -f2)
	MYSQLPASS=$(cat ~/.my.cnf | grep pass | cut -d'=' -f2 | sed -e 's/^"//'  -e 's/"$//')
}
# GET Information Function
MYSQLINFO()
{
	# Get The MySQL Host
	MYSQLHOST=$(grep mysqlhost /etc/easyengine/ee.conf | awk '{print($3)}')

	# MySQL Default Host: localhost
	if [[ $MYSQLHOST = "" ]]
	then
		MYSQLHOST=localhost
	fi
	
	if [ -f ~/.my.cnf ]
	then
		MYSQLROOT
	else
		# Verify MySQL Credentials
		MYSQLUSERPASS
	fi

	# Verify MySQL Credentials
	MYSQLPASSCHECK

	# Replace Dot With Underscore In $DOMAIN Name
	REPLACEDOT=$(echo $DOMAIN | tr '.' '_')

	# Check Use Default DB Name Or Custom DB Name
	grep customdbname /etc/easyengine/ee.conf | grep -i true &>> /dev/null

	if [ $? -eq 0 ]
	then
		read -p "Enter The MySQL Database Name [$REPLACEDOT]: " WPDBNAME
	fi

	# If customdbname = false 
	# 		Then It Never Ask For MySQL Database Name In This Case $WPDBNAME Is Empty
	# If customdbname = true
	#		User Enter Custom Databse Name Then WPDBNAME Is Not Empty & We Used Provided Database Name
 	#		If User Pressed Enter Then $WPDBNAME Is Empty

	if [[ $WPDBNAME = "" ]]
	then
		WPDBNAME=$REPLACEDOT
	fi
}

EEWPDBPREFIX()
{
	# Get The WordPress Database Table Prefix
	WPDBPREFIX=$(grep wpdbprefix /etc/easyengine/ee.conf | awk '{print($3)}')
	
	# Display WPDBPREFIX Valid Characters Warning & Try Again
	while [ $(echo $WPDBPREFIX | grep  '[^[:alnum:] _]') ]
	do
		echo -e "\033[31mWarning: \033[34mTable Prefix Can Only Contain Numbers, Letters, And Underscores.\e[0m"
		# For Proper read Command Output
		stty echo
		read -p "Enter The MySQL Database Table Prefix [wp_]: " WPDBPREFIX
	done

	# WordPress Database Table Prefix Default: wp_
	if [[ $WPDBPREFIX = "" ]]
	then
		WPDBPREFIX=wp_
	fi
}

FIXMYSQLUSER16()
{
	# Fix MySQL USER ERROR 1470 (HY000)
	MYSQLUSER16=$(echo -n $WPDBUSER | wc -c)

	if [[ $MYSQLUSER16 -gt 16 ]]
	then
		echo MySQL Database Username $WPDBUSER = $MYSQLUSER16 &>> $INSTALLLOG
		REPLACEDOT16=$(echo $REPLACEDOT | cut -c1-16)

		echo -e "\033[31mERROR 1470 (HY000): $WPDBUSER Is Too Long For MySQL Username\e[0m"
		# Turn Off Echo For Passwords
		stty echo
		read -p "Enter The MySQL Database Username [$REPLACEDOT16]: " WPDBUSER

		if [[ $WPDBUSER = "" ]]
		then
			WPDBUSER=$REPLACEDOT16
		fi

	fi

}

EECREATEDATABASE()
{
	# Create Database
	mysql -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASS -e "create database \`$WPDBNAME\`" \
	|| OwnError "Unable To Create $WPDBNAME Database"

	# Check Use Default DB User Or Custom DB User
	WPDBRANDOMPASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n1)
	grep customdbuser /etc/easyengine/ee.conf | grep -i true &>> /dev/null

	if [ $? -eq 0 ]
	then
		read -p "Enter The MySQL Database Username [$REPLACEDOT]: " WPDBUSER

		if [[ $WPDBUSER = "" ]]
		then
			WPDBUSER=$REPLACEDOT
		fi

		# Fix MySQL USER ERROR 1470 (HY000)
		FIXMYSQLUSER16
		
		# Turn Off Echo For Passwords
		stty -echo
		read -p "Enter The MySQL Database Password [$WPDBRANDOMPASS]: " WPDBPASS
		stty echo
		echo
	fi

	if [[ $WPDBUSER = "" ]]
	then
		WPDBUSER=$REPLACEDOT
		# Fix MySQL USER ERROR 1470 (HY000)
		FIXMYSQLUSER16
	fi

	if [[ $WPDBPASS = "" ]]
	then
		WPDBPASS=$WPDBRANDOMPASS
	fi

	# Create Separate User & Grant Permission
	echo -e "WPDBNAME = $WPDBNAME \nWPDBUSER = $WPDBUSER \nWPDBPASS = $WPDBPASS" &>> $INSTALLLOG
	mysql -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASS -e "create user '$WPDBUSER'@'$MYSQLHOST' identified by '$WPDBPASS'"
	mysql -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASS -e "grant all privileges on \`$WPDBNAME\`.* to '$WPDBUSER'@'$MYSQLHOST'"
	mysql -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASS -e "flush privileges"
}

PHPUSERINFO()
{
	# PHP User
	PHPUSER=$(grep ^user /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2 | cut -d' ' -f2) \
	|| OwnError "Unable To Find Out PHP Username"
}

EEINFO()
{
	# Nginx Information
	NGINXVER=$(nginx -v 2>&1 | cut -d':' -f2 | cut -d' ' -f2)
	NGINXUSER=$(grep ^user /etc/nginx/nginx.conf | cut -d' ' -f2 | cut -d';' -f1)
	NGINXPROCESSES=$(grep worker_processes /etc/nginx/nginx.conf | cut -d' ' -f2 | cut -d';' -f1)
	NGINXCONNECTIONS=$(grep worker_connections /etc/nginx/nginx.conf | cut -d' ' -f2 | cut -d';' -f1)
	NGINXKEEPALIVE=$(grep keepalive_timeout /etc/nginx/nginx.conf | cut -d' ' -f2 | cut -d';' -f1)
	FASTCGITIMEOUT=$(grep fastcgi_read_timeout /etc/nginx/nginx.conf | cut -d' ' -f2 | cut -d';' -f1)
	CLIENTMAXBODYSIZE=$(grep client_max_body_size /etc/nginx/nginx.conf | cut -d' ' -f2 | cut -d';' -f1)
	NGINXALLOWEDIPADD=$(grep ^allow /etc/nginx/common/acl.conf | cut -d' ' -f2 | cut -d';' -f1 | tr '\n' ' ')

	echo -e "\033[34mNginx ($NGINXVER) Information:\n\e[0m"
	echo -e "\033[34mNginx User:\t\t\t \033[37m$NGINXUSER\e[0m"
	echo -e "\033[34mNginx worker_processes:\t\t \033[37m$NGINXPROCESSES\e[0m"
	echo -e "\033[34mNginx worker_connections:\t \033[37m$NGINXCONNECTIONS\e[0m"
	echo -e "\033[34mNginx keepalive_timeout:\t \033[37m$NGINXKEEPALIVE\e[0m"
	echo -e "\033[34mNginx fastcgi_read_timeout:\t \033[37m$FASTCGITIMEOUT\e[0m"
	echo -e "\033[34mNginx client_max_body_size:\t \033[37m$CLIENTMAXBODYSIZE\e[0m"
	echo -e "\033[34mNginx Allowed IP Address:\t \033[37m$NGINXALLOWEDIPADD\e[0m"

	# PHP Information
	# Collect Information From php.ini
	PHPUSERINFO
	PHPVER=$(php -v | head -n1 | cut -d' ' -f2 | cut -d'+' -f1)
	PHPEXPOSE=$(grep ^expose_php /etc/php5/fpm/php.ini | cut -d'=' -f2 | cut -d' ' -f2)
	PHPPOSTMAXSIZE=$(grep post_max_size /etc/php5/fpm/php.ini | cut -d'=' -f2 | cut -d' ' -f2)
	PHPUPLOADMAXFSIZE=$(grep upload_max_filesize /etc/php5/fpm/php.ini | cut -d'=' -f2 | cut -d' ' -f2)
	PHPMAXEXECUTIONTIME=$(grep max_execution_time /etc/php5/fpm/php.ini | cut -d'=' -f2 | cut -d' ' -f2)

	# Collect Information From www.conf
	PHPPINGPATH=$(grep ^ping.path /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)
	PHPSTATUSPATH=$(grep ^pm.status_path /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)
	PMMAXREQUEST=$(grep ^pm.max_requests /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)
	PMMAXCHILDREN=$(grep ^pm.max_children /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)
	PMSTARTSERVERS=$(grep ^pm.start_servers /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)
	PMMINSPARESERVERS=$(grep ^pm.min_spare_servers /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)
	PMMAXSPARESERVERS=$(grep ^pm.max_spare_servers /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)
	PHPREQUESTTERMINATE=$(grep ^request_terminate_timeout /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)
	PHPFASTCGIREQUEST=$(grep ^listen /etc/php5/fpm/pool.d/www.conf | cut -d'=' -f2| cut -d' ' -f2)

	echo -e "\033[34m\n\nPHP ($PHPVER) Information:\n\e[0m"
	echo -e "\033[34mPHP User:\t\t\t \033[37m$PHPUSER\e[0m"
	echo -e "\033[34mPHP expose_php:\t\t\t \033[37m$PHPEXPOSE\e[0m"
	echo -e "\033[34mPHP post_max_size:\t\t \033[37m$PHPPOSTMAXSIZE\e[0m"
	echo -e "\033[34mPHP upload_max_filesize:\t \033[37m$PHPUPLOADMAXFSIZE\e[0m"
	echo -e "\033[34mPHP max_execution_time:\t\t \033[37m$PHPMAXEXECUTIONTIME\n\e[0m"

	echo -e "\033[34mPHP ping.path:\t\t\t \033[37m$PHPPINGPATH\e[0m"
	echo -e "\033[34mPHP pm.status_path:\t\t \033[37m$PHPSTATUSPATH\e[0m"
	echo -e "\033[34mPHP pm.max_requests:\t\t \033[37m$PMMAXREQUEST\e[0m"
	echo -e "\033[34mPHP pm.max_children:\t\t \033[37m$PMMAXCHILDREN\e[0m"
	echo -e "\033[34mPHP pm.start_servers:\t\t \033[37m$PMSTARTSERVERS\e[0m"
	echo -e "\033[34mPHP pm.min_spare_servers:\t \033[37m$PMMINSPARESERVERS\e[0m"
	echo -e "\033[34mPHP pm.max_spare_servers:\t \033[37m$PMMAXSPARESERVERS\e[0m"
	echo -e "\033[34mPHP request_terminate_timeout:\t \033[37m$PHPREQUESTTERMINATE\e[0m"
	echo -e "\033[34mPHP Fastcgi Listen:\t\t \033[37m$PHPFASTCGIREQUEST\e[0m"

	# MySQL Information
	MYSQLVER=$(mysql -V | awk '{print($5)}' | cut -d ',' -f1)
	MYSQLUSER=$(grep ^user /etc/mysql/my.cnf | awk '{print($3)}')
	MYSQLPORT=$(mysql -e "show variables" | grep ^port | awk '{print($2)}')
	MYSQLSOCKET=$(mysql -e "show variables" | grep "^socket" | awk '{print($2)}')
	MYSQLDATADIR=$(mysql -e "show variables" | grep datadir | awk '{print($2)}')
	MYSQLWAITTIMEOUT=$(mysql -e "show variables" | grep ^wait_timeout | awk '{print($2)}')
	MYSQLINTERACTIVE=$(mysql -e "show variables" | grep ^interactive_timeout | awk '{print($2)}')
	MYSQLMAXCONNECTION=$(mysql -e "show variables" | grep "^max_connections" | awk '{print($2)}')
	MYSQLMAXUSEDCONNECTION=$(mysql -e "show global status" | grep Max_used_connections | awk '{print($2)}')

	echo -e "\033[34m\n\nMySQL ($MYSQLVER) Information:\n\e[0m"
	echo -e "\033[34mMySQL User:\t\t\t \033[37m$MYSQLUSER\e[0m"
	echo -e "\033[34mMySQL port:\t\t\t \033[37m$MYSQLPORT\e[0m"
	echo -e "\033[34mMySQL wait_timeout:\t\t \033[37m$MYSQLWAITTIMEOUT\e[0m"
	echo -e "\033[34mMySQL interactive_timeout:\t \033[37m$MYSQLINTERACTIVE\e[0m"
	echo -e "\033[34mMySQL Max_used_connections:\t \033[37m$MYSQLMAXUSEDCONNECTION/$MYSQLMAXCONNECTION\e[0m"
	echo -e "\033[34mMySQL datadir:\t\t\t \033[37m$MYSQLDATADIR\e[0m"
	echo -e "\033[34mMySQL socket:\t\t\t \033[37m$MYSQLSOCKET\e[0m"

	# Common Locations:
	echo -e "\033[34m\n\nEasyEngine (ee) Common Locations:\n\e[0m"
	echo -e "\033[34mphpMyAdmin:\t\t\t \033[37mhttp://example.com/pma\e[0m"
	echo -e "\033[34mPHP Status:\t\t\t \033[37mhttp://example.com/status\e[0m"
	echo -e "\033[34mNginx Status:\t\t\t \033[37mhttp://example.com/nginx_status\e[0m"
	echo -e "\033[34mOpcache & Memcache Status:\t \033[37mhttp://example.com/ee/\e[0m"
	echo -e "\033[34mEasyEngine Log File:\t\t \033[37m/var/log/easyengine/install.log\e[0m"
	echo -e "\033[34mEasyEngine Configuration File:\t \033[37m/etc/easyengine/ee.conf\e[0m"

}

EESITEINFO()
{
	# Display The Specific Site Configuration
	SITESTATUS=$(ls /etc/nginx/sites-enabled/$DOMAIN &> /dev/null && echo Enable || echo Disable)
	SITEINFO=$(head -n1 /etc/nginx/sites-available/$DOMAIN | grep "NGINX CONFIGURATION" | rev | cut -d' ' -f3,4,5,6,7 | rev | cut -d ' ' -f2,3,4,5)
	ACCESSLOG=$(grep access_log /etc/nginx/sites-available/$DOMAIN | grep "/var/log/nginx/" | awk '{print($2)}' | cut -d ';' -f1)
	ERRORLOG=$(grep error_log /etc/nginx/sites-available/$DOMAIN | grep "/var/log/nginx/" | awk '{print($2)}' | cut -d ';' -f1)
	WEBROOT=$(grep root /etc/nginx/sites-available/$DOMAIN | grep htdocs | awk '{print($2)}'  | cut -d ';' -f1)
	WPDBNAME=$(grep DB_NAME /var/www/$DOMAIN/wp-config.php 2> /dev/null | cut -d"'" -f4)

	echo -e "\033[34m$DOMAIN Information:\n\e[0m"
	echo -e "\033[34mNginx Configuration:\t\t \033[37m$SITEINFO ($SITESTATUS)\e[0m"
	echo -e "\033[34mNginx access_log:\t\t \033[37m$ACCESSLOG\e[0m"
	echo -e "\033[34mNginx error_log:\t\t \033[37m$ERRORLOG\e[0m"
	echo -e "\033[34mNginx root:\t\t\t \033[37m$WEBROOT\e[0m"
	echo -e "\033[34m$DOMAIN Database:\t\t \033[37m$WPDBNAME\e[0m"
}

NGINXBUCKETSIZE()
{
	nginx -t 2>&1 | grep server_names_hash_bucket_size &>> $INSTALLLOG
	if [ $? -eq 0 ]
	then
		NGINXCALCULATION=$(echo "l($(ls /etc/nginx/sites-enabled/ | wc -c))/l(2)+2" | bc -l)
		NGINXSETBUCKET=$(echo "2^$NGINXCALCULATION" | bc -l 2> /dev/null)
		sed -i "s/.*server_names_hash_bucket_size.*/\tserver_names_hash_bucket_size $NGINXSETBUCKET;/" /etc/nginx/nginx.conf		
	fi
}

NGINXRELOAD()
{
	# Check Nginx server_names_hash_bucket_size Value
	NGINXBUCKETSIZE

	# Reload Nginx Configuration
	echo -e "\033[34mReloading Nginx Configuration, Please Wait...\e[0m"
	(nginx -t && service nginx reload) &>> $INSTALLLOG || OwnError "Unable To Reload Nginx"
}

NGINXRESTART()
{
	# Check Nginx server_names_hash_bucket_size Value
	NGINXBUCKETSIZE

	# Test & Reload Nginx
	echo -e "\033[34mRestarting Nginx Configuration, Please Wait...\e[0m"
	(nginx -t && service nginx restart) &>> $INSTALLLOG || OwnError "Unable To Restart Nginx"
}

PHPRESTART()
{
	# Reload PHP
	echo -e "\033[34mRestarting PHP5-FPM Configuration, Please Wait...\e[0m"
	service php5-fpm restart &>> $INSTALLLOG || OwnError "Unable To Restart PHP5-FPM"
}



# EE Domian Functions
EESITENAME()
{
	# Check SITENAME Is Empty Or Not
	if [ -z "$SITENAMECHECK" ]
	then
		# Ask Users To Enter Domain Name
		read -p "Enter Domain Name: " SITENAMECHECK
		# Remove http://  https:// & www.
		DOMAIN=$(echo $SITENAMECHECK | tr 'A-Z' 'a-z' |  sed "s'http://''" | sed "s'https://''" | sed "s'www.''" | sed "s'/''")
	else
		# Remove http://  https:// & www.
		DOMAIN=$(echo $SITENAMECHECK | tr 'A-Z' 'a-z' |  sed "s'http://''" | sed "s'https://''" | sed "s'www.''" | sed "s'/''")
	fi

	# Remove http://  https:// For WordPress Setup (www.example.com)
	WWWDOMAIN=$(echo $SITENAMECHECK | tr 'A-Z' 'a-z' |  sed "s'http://''" | sed "s'https://''" | sed "s'/''")
}

NGINXSYMBOLICLINK()
{
	# Creating Symbolic Link
	echo -e "\033[34mCreating Symbolic Link For $DOMAIN\e[0m"
	ln -s /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/ \
	|| OwnError "Unable To Create Symbolic Link For $DOMAIN"
}

EEDOMAINSETUP()
{
	#Check The Nginx Configuration Exist For $DOMAIN
	ls /etc/nginx/sites-available/$DOMAIN &> $ERRORLOG

	if [ $? -ne 0 ]
	then
		# Creating Website $DOMAIN
		echo -e "\033[34mCreating $DOMAIN, Please Wait...\e[0m"
		sed "s/example.com/$DOMAIN/g" \
		/usr/share/easyengine/nginx/$NGINXCONF \
		> /etc/nginx/sites-available/$DOMAIN \
		|| OwnError "Unable To Create Nginx Configuration File For $DOMAIN"

		# Creating Symbolic Link
		NGINXSYMBOLICLINK

		# Creating Htdocs & Logs Directory
		echo -e "\033[34mCreating htdocs & logs Directory\e[0m"
		mkdir -p /var/www/$DOMAIN/htdocs && mkdir -p /var/www/$DOMAIN/logs \
		|| OwnError "Unable To Create htdocs & logs Directory"

		# Creating Symbolic Links For Logs
		echo -e "\033[34mCreating Symbolic Link For Logs\e[0m"
		ln -s /var/log/nginx/$DOMAIN.access.log /var/www/$DOMAIN/logs/access.log \
		&& ln -s /var/log/nginx/$DOMAIN.error.log /var/www/$DOMAIN/logs/error.log \
		|| OwnError "Unable To Create Symbolic Link For $DOMAIN Logs"
	else
		OwnError "$DOMAIN Already Exist"
	fi
}

EEWPSETUP()
{
	# Download Latest WordPress
	echo -e "\033[34mDownloading WordPress, Please Wait...\e[0m"
	wget -cqO /var/www/$DOMAIN/htdocs/latest.tar.gz  \
	http://wordpress.org/latest.tar.gz \
	|| OwnError "Unable To Download WordPress"

	# Extracting WordPress
	tar --strip-components=1 -zxf /var/www/$DOMAIN/htdocs/latest.tar.gz \
	-C /var/www/$DOMAIN/htdocs/ \
	|| OwnError "Unable To Extract WordPress"

	# Removing WordPress Archive
	rm /var/www/$DOMAIN/htdocs/latest.tar.gz

	# Call MYSQLINFO Function For MySQL Values
	MYSQLINFO
	EEWPDBPREFIX
	EECREATEDATABASE

	# Modify wp-config.php & Move Outside The Webroot
	cp /var/www/$DOMAIN/htdocs/wp-config-sample.php \
	/var/www/$DOMAIN/wp-config.php

	sed -i "s/database_name_here/$WPDBNAME/" \
	/var/www/$DOMAIN/wp-config.php

	sed -i "s/username_here/$WPDBUSER/" \
	/var/www/$DOMAIN/wp-config.php
				
	sed -i "s/password_here/$WPDBPASS/" \
	/var/www/$DOMAIN/wp-config.php

	sed -i "s/localhost/$MYSQLHOST/" \
	/var/www/$DOMAIN/wp-config.php

	sed -i "s/wp_/$WPDBPREFIX/" \
	/var/www/$DOMAIN/wp-config.php

	printf '%s\n' "g/put your unique phrase here/d" \
	a "$(curl -sL https://api.wordpress.org/secret-key/1.1/salt/)" . w \
	| ed -s /var/www/$DOMAIN/wp-config.php
}

EEWPDBSETUP()
{
	# Get WordPress Site Title
	#echo -e "\033[34mWordPress Information Required...\e[0m"

	# WordPress Default User: admin
	WPADMINUSER=$(grep wpadminuser /etc/easyengine/ee.conf | awk '{print($3)}')
	if [[ $WPADMINUSER = "" ]]
	then
		WPADMINUSER=admin
	fi

	# WordPress Default Password: Random Password
	WPADMINPASS=$(grep wpadminpass /etc/easyengine/ee.conf | awk '{print($3)}')
	if [[ $WPADMINPASS = "" ]]
	then
		WPADMINPASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n1)
	fi
	
	# WordPress Default Email: `git config user.email`
	WPADMINEMAIL=$(grep wpadminemail /etc/easyengine/ee.conf | awk '{print($3)}')
	if [[ $WPADMINEMAIL = "" ]]
	then
		WPADMINEMAIL=`git config user.email`
	fi

	# Create WordPress Tables
	echo -e "\033[34mSetting Up WordPress, Please Wait...\e[0m"
	cd /var/www/$DOMAIN/htdocs || OwnError "Unable To Change Directory To Install WordPress"
	wp core install --allow-root  --url=$WWWDOMAIN --title="$WWWDOMAIN" \
	--admin_name=$WPADMINUSER --admin_password=$WPADMINPASS --admin_email=$WPADMINEMAIL &>> $INSTALLLOG \
	|| OwnError "Unable To Create WordPress Tables For $DOMAIN"
	
	# Update WordPress Permalink Structure Day and Postname
	echo -e "\033[34mUpdating WordPress Permalink, Please Wait...\e[0m"
	wp rewrite structure --allow-root /%year%/%monthnum%/%day%/%postname%/ &>> $INSTALLLOG \
	|| OwnError "Unable To Update WordPress Permalink For $DOMAIN"
}

EEPERMISSION()
{
	# Call PHPUSERINFO Function For PHP User Details
	PHPUSERINFO

	# Change Ownership
	echo -e "\033[34mChanging Ownership\e[0m"
	chown -R $PHPUSER:$PHPUSER /var/www/$DOMAIN/ || OwnError "Unable To Change Ownership For $DOMAIN"

	# Reload Nginx Configuration
	NGINXRELOAD
}


# NGINX Configuration Function
SETUPDOMAIN()
{
	# Check SITENAME Is Empty Or Not
	EESITENAME

	# Creating Website $DOMAIN
	EEDOMAINSETUP

	# Setup WordPress Webroot & Database
	EEWPSETUP
	EEWPDBSETUP
}

PERMISSIONANDGIT()
{
	# Change Webroot Permission
	EEPERMISSION

	# Take Nginx Configuration In Git Version Control
	EEGITDIR=/etc/nginx
	EEGITMESSAGE="Create Website With $WPNETWORKSITE $WPCACHEOPTION Option: $DOMAIN"
	EEGITCOMMIT
}

EEOPMEMCACHE()
{
	# Opcache Settings
	if [ ! -d /var/www/eeadmin/htdocs/php/opcache ]
	then
		mkdir -p /var/www/eeadmin/htdocs/php/opcache || OwnError "Unable To Create Opcache Directory"

		# Download Opcache Status Files
		wget -cqO /var/www/eeadmin/htdocs/php/opcache/opcache.php https://raw.github.com/rlerdorf/opcache-status/master/opcache.php
		wget -cqO /var/www/eeadmin/htdocs/php/opcache/opgui.php https://raw.github.com/amnuts/opcache-gui/master/index.php
		wget -cqO /var/www/eeadmin/htdocs/php/opcache/ocp.php https://gist.github.com/ck-on/4959032/raw/0b871b345fd6cfcd6d2be030c1f33d1ad6a475cb/ocp.php
	fi

	# Memcache Settings
	if [ ! -d /var/www/eeadmin/htdocs/php/memcache ]
	then
		mkdir -p /var/www/eeadmin/htdocs/php/memcache || OwnError "Unable To Create Memcache Directory"

		# Download phpMemcachedAdmin
		wget -cqO /var/www/eeadmin/htdocs/php/memcache/memcache.tar.gz http://phpmemcacheadmin.googlecode.com/files/phpMemcachedAdmin-1.2.2-r262.tar.gz

		# Extract phpMemcachedAdmin
		tar -zxf /var/www/eeadmin/htdocs/php/memcache/memcache.tar.gz -C /var/www/eeadmin/htdocs/php/memcache

		# Remove Unwanted Files
		rm -f /var/www/eeadmin/htdocs/php/memcache/memcache.tar.gz
	fi
}

TOTALCACHENGINX()
{
	# Installing W3 Total Cache
	cd /var/www/$DOMAIN/htdocs/
	echo -e "\033[34mInstalling W3 Total Cache Plugin, Please Wait...\e[0m"
	wp plugin --allow-root install w3-total-cache &>> $INSTALLLOG || OwnError "Unable To Install W3 Total Cache Plugin"

	# Activate W3 Total Cache
	wp plugin --allow-root activate w3-total-cache $NETWORKACTIVATE &>> $INSTALLLOG || OwnError "Unable To Activate W3 Total Cache Plugin"

	# Install Opcache & Memcache
	EEOPMEMCACHE
}

SUPERCACHENGINX()
{
	# Installing WP Super Cache
	cd /var/www/$DOMAIN/htdocs/
	echo -e "\033[34mInstalling WP Super Cache Plugin, Please Wait...\e[0m"
	wp plugin --allow-root install wp-super-cache &>> $INSTALLLOG || OwnError "Unable To Install WP Super Cache Plugin"

	# Activate WP Super Cache
	wp plugin --allow-root activate wp-super-cache $NETWORKACTIVATE &>> $INSTALLLOG || OwnError "Unable To Activate WP Super Cache Plugin"
}

NGINXHELPER()
{
	# Installing Nginx Helper
	cd /var/www/$DOMAIN/htdocs/
	echo -e "\033[34mInstalling Nginx Helper Plugin, Please Wait...\e[0m"
	wp plugin --allow-root install nginx-helper &>> $INSTALLLOG || OwnError "Unable To Install Nginx Helper"

	# Activate Nginx Helper
	wp plugin --allow-root activate nginx-helper $NETWORKACTIVATE &>> $INSTALLLOG || OwnError "Unable To Activate Nginx Helper Plugin"
}


# Setup Wordpress Network
SETUPWPNETWORK()
{
	# Prepare wp-config.php File Foe WordPress Multisite With SubDirectory
	cd /var/www/$DOMAIN/htdocs || OwnError "Unable To Change Directory"
	wp core install-network --allow-root --title="$WWWDOMAIN" $WPSUBDOMAINS &>> $INSTALLLOG || OwnError "Unable To Setup WordPress SubDirectory Network"

	sed -i "/WP_DEBUG/a \define('WP_ALLOW_MULTISITE', true);" /var/www/$DOMAIN/wp-config.php
	sed -i "/WP_ALLOW_MULTISITE/a \define('WPMU_ACCEL_REDIRECT', true);" /var/www/$DOMAIN/wp-config.php
	
	# Remove index.php from permalink
	# Install Nginx Helper
	NGINXHELPER
}


# Remove Database
REMOVEDB()
{
	# HTML & PHP Website Doesn't Have Database
	head -n1 /etc/nginx/sites-available/$DOMAIN | egrep -e 'HTML|PHP' &>> $INSTALLLOG
	if [ $? -ne 0 ]
	then
		# MySQL Information
		MYSQLROOT
		WPDBNAME=$(grep DB_NAME /var/www/$DOMAIN/*-config.php | cut -d"'" -f4)
		WPDBUSER=$(grep DB_USER /var/www/$DOMAIN/*-config.php | cut -d"'" -f4)
		WPDBPASS=$(grep DB_PASS /var/www/$DOMAIN/*-config.php | cut -d"'" -f4)
		MYSQLHOST=$(grep DB_HOST /var/www/$DOMAIN/*-config.php | cut -d"'" -f4)
		echo -e " WPDBNAME = $WPDBNAME \n WPDBUSER = $WPDBUSER \n MYSQLHOST = $MYSQLHOST"

		# Remove Database
		# For Proper read Command Output
		stty echo
		read -p "Are You Sure To Drop $WPDBNAME Database (y/n): " ANSWER

		if [ "$ANSWER" = "y" ]
		then
			# Remove Database
			mysql -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASS -e "drop database \`$WPDBNAME\`" \
			|| OwnError "Unable To Drop $WPDBNAME Database"
			# Remove Database User
			mysql -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASS -e "drop user '$WPDBUSER'@'$MYSQLHOST'" \
			|| OwnError "Unable To Drop Database User $WPDBUSER"
			mysql -h $MYSQLHOST -u $MYSQLUSER -p$MYSQLPASS -e "flush privileges" \
			|| OwnError "Unable To Flush MySQL Privileges"

		else
			# User Denied Messages
			echo -e "\033[31mUser Denied To Drop $WPDBNAME Database.\e[0m"
		fi
	else
		echo -e "\033[31mNo Database Found For $DOMAIN\e[0m"
	fi
}

REMOVEFILES()
{
	# Remove Webroot
	# For Proper read Command Output
	stty echo
	read -p "Are You Sure To Remove $DOMAIN Webroot (y/n): " ANSWER

	if [ "$ANSWER" = "y" ]
	then
		# Remove Webroot
		rm -rf /var/www/$DOMAIN	|| OwnError "Unable To Remove $DOMAIN Webroot"
	else
		# User Denied Messages
		echo -e "\033[31mUser Denied To Remove $DOMAIN Webroot.\e[0m"
	fi
}

REMOVENGINXCONF()
{
	# Remove Nginx Configuration
	# For Proper read Command Output
	stty echo
	read -p "Are You Sure To Remove $DOMAIN Nginx Configuration (y/n): " ANSWER

	if [ "$ANSWER" = "y" ]
	then
		# Remove Webroot
		rm -rf /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/$DOMAIN \
		|| OwnError "Unable To Remove $DOMAIN Nginx Configuration"
	else
		# User Denied Messages
		echo -e "\033[31mUser Denied To Remove $DOMAIN Nginx Configuration.\e[0m"
	fi
}


# Easy Engine Version
if [ "$1" = "version" ] || [ "$1" = "--version" ] || [ "$1" = "-v" ]
then

	# Display Easy Engine Version
	echo "easyengine version: 1.2.1"

# Easy Engine Info
elif [ "$1" = "info" ]
then

		# Get Nginx PHP & MySQL Information
		EEINFO

# Easy Engine Help
elif [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]
then

	# Display Man Pages
	man ee


# Easy Engine System Settings
elif [ "$1" = "system" ]
then

	# Check Auto Assume Yes Or No To Apt-Get
	APTASSUMEYES

	# Define Nginx Package
	if [ "$LINUX_DISTRO" == "Ubuntu" ]
	then
		NGINXPACKAGE=nginx-custom

	elif [ "$LINUX_DISTRO" == "Debian" ]
	then
		NGINXPACKAGE=nginx-full
	fi


	# Easy Engine Install
	if [ "$2" = "install" ]
	then

		if [ "$3" = "nginx" ]
		then

			# Install Python Software Properties
			PYTHONSOFTWARE

			# Add Nginx Launchpad Repository
			NGINXREPO

			# Fix GPG Key Problems
			GPGKEY

			# Update The APT Cache
			UPDATEAPT			

			# Install Nginx
			INSTALLNGINX

			# Personal Settings For Nginx
			COMMONNGINX

			# Restart Nginx To Take Effect Of COMMONNGINX Functions
			NGINXRESTART

			# Initialise Git
			EEGITDIR=/etc/nginx/
			EEGITINIT
			
			# Display Success Message
			echo -e "\033[34mNginx Successfully Installed\e[0m"

		elif [ "$3" = "php" ]
		then

			# Install Python Software Properties
			PYTHONSOFTWARE

			# Add PHP Launchpad Repository
			PHPREPO

			# Fix GPG Key Problems
			GPGKEY

			# Update The APT Cache
			UPDATEAPT

			# Install PHP5
			INSTALLPHP

			# Personal Settings For PHP
			COMMONPHP

			# Restart PHP To Take Effect Of COMMONPHP Functions
			PHPRESTART
			
			# Install WP-CLI
			WP-CLI

			# Initialise Git
			EEGITDIR=/etc/php5/
			EEGITINIT

			# Display Success Message
			echo -e "\033[34mPHP5 & WP-CLI Successfully Installed\e[0m"

		elif [ "$3" = "phpmyadmin" ] || [ "$3" = "pma" ]
		then

			# Install PMA/phpMyAdmin
			INSTALLPMA

			# Initialise Git
			#EEGITDIR=/var/www/eeadmin/htdocs/db/pma/
			#EEGITINIT

			# Display Success Message
			echo -e "\033[34mphpMyAdmin Successfully Installed\e[0m"

		elif [ "$3" = "mysql" ]
		then

			# Update The APT Cache
			UPDATEAPT

			# Install MySQL
			INSTALLMYSQL

			# Initialize Git
			EEGITDIR=/etc/mysql/
			EEGITINIT
			
			# Display Success Message
			echo -e "\033[34mMySQL Successfully Installed\e[0m"

		elif [ "$3" = "postfix" ]
		then

			# Update The APT Cache
			UPDATEAPT
			
			# Install Postfix
			INSTALLPOSTFIX

			# Initialize Git
			EEGITDIR=/etc/postfix/
			EEGITINIT
			
			# Display Success Message
			echo -e "\033[34mPostfix Successfully Installed\e[0m"

		elif [ "$3" = "all" ] || [ "$3" = "" ]
		then
			
			# Install Python Software Properties
			PYTHONSOFTWARE

            # Add Nginx Launchpad Repository
			NGINXREPO
			
			# Add PHP Launchpad Repository
			PHPREPO

			# Fix GPG Key Problems
			GPGKEY

			# Update The APT Cache
			UPDATEAPT

			# Install Nginx PHP5 MySQL Postfix
			INSTALLALL

			# Personal Settings For Nginx
			COMMONNGINX

			# Reload Nginx To Take Effect Of COMMONNGINX Functions
			NGINXRESTART

			# Personal Settings For PHP
			COMMONPHP

			# Restart PHP To Take Effect Of COMMONPHP Functions
			PHPRESTART

			# Install WP-CLI
			WP-CLI

			# Install PMA/phpMyAdmin
			INSTALLPMA

			# Initialize Git
			EEGITDIR=/etc/nginx/
			EEGITINIT

			# Initialize Git
			EEGITDIR=/etc/php5/
			EEGITINIT

			# Initialize Git
			EEGITDIR=/etc/mysql/
			EEGITINIT

			# Initialize Git
			#EEGITDIR=/var/www/eeadmin/htdocs/db/pma/
			#EEGITINIT

			# Initialize Git
			EEGITDIR=/etc/postfix/
			EEGITINIT

			# Display Success Message
			echo -e "\033[34mNginx PHP5 WP-CLI MySQL Postfix phpMyAdmin Successfully Installed\e[0m"
			echo -e "\033[34mYou Can Now Create Your First WordPress Site Powered By Nginx Using:\e[0m"
			echo -e "\033[37mee site create example.com --wp\e[0m"

		fi

	# Easy Engine Remove
	elif [ "$2" = "remove" ]
	then
		
		if [ "$3" = "nginx" ]
		then

			# Remove Nginx
			REMOVENGINX
			
			# Remove Unwanted Packages
			AUTOREMOVE
			
			# Display Success Message
			echo -e "\033[34mNginx Successfully Removed\e[0m"

		elif [ "$3" = "php" ]
		then

			# Remove PHP5
			REMOVEPHP
			REMOVEWPCLI
			
			# Remove Unwanted Packages
			AUTOREMOVE
						
			# Display Success Message
			echo -e "\033[34mPHP5 & WP-CLI Successfully Removed\e[0m"

		elif [ "$3" = "phpmyadmin" ]  || [ "$3" = "pma" ]
		then

			# Remove PMA/phpMyAdmin
			REMOVEPMA
			
			# Display Success Message
			echo -e "\033[34mphpMyAdmin Successfully Removed\e[0m"

		elif [ "$3" = "mysql" ]
		then

			# Remove MySQL
			REMOVEMYSQL
			
			# Remove Unwanted Packages
			AUTOREMOVE
			
			# Display Success Message
			echo -e "\033[34mMySQL Successfully Removed\e[0m"

		elif [ "$3" = "postfix" ]
		then

			# Remove Postfix
			REMOVEPOSTFIX
			
			# Remove Unwanted Packages
			AUTOREMOVE
			
			# Display Success Message
			echo -e "\033[34mPostfix Successfully Removed\e[0m"

		elif [ "$3" = "all" ] || [ "$3" = "" ]
		then

			# Remove Nginx PHP5 MySQL Postfix
			REMOVEALL
			
			# Remove Unwanted Packages
			AUTOREMOVE
			REMOVEWPCLI
			REMOVEPMA

			# Display Success Message
			echo -e "\033[34mNginx PHP5 WP-CLI MySQL Postfix phpMyAdmin Successfully Removed\e[0m"

		fi

	# Easy Engine Purge
	elif [ "$2" = "purge" ]
	then
		
		if [ "$3" = "nginx" ]
		then

			# Purge Nginx
			PURGENGINX
			
			# Remove Unwanted Packages
			AUTOREMOVE
			
			# Display Success Message
			echo -e "\033[34mNginx Successfully Purged\e[0m"

		elif [ "$3" = "php" ]
		then

			# Purge PHP5
			PURGEPHP
			REMOVEWPCLI
			
			# Remove Unwanted Packages
			AUTOREMOVE

			# Display Success Message
			echo -e "\033[34mPHP5 & WP-CLI Successfully Purged\e[0m"

		elif [ "$3" = "phpmyadmin" ]  || [ "$3" = "pma" ]
		then

			# Purge PMA/phpMyAdmin
			REMOVEPMA
			
			# Display Success Message
			echo -e "\033[34mphpMyAdmin Successfully Purged\e[0m"

		elif [ "$3" = "mysql" ]
		then

			# Purge MySQL
			PURGEMYSQL
			
			# Remove Unwanted Packages
			AUTOREMOVE

			# Display Success Message
			echo -e "\033[34mMySQL Successfully Purged\e[0m"

		elif [ "$3" = "postfix" ]
		then

			# Purge Postfix
			PURGEPOSTFIX
			
			# Remove Unwanted Packages
			AUTOREMOVE

			# Display Success Message
			echo -e "\033[34mPostfix Successfully Purged\e[0m"

		elif [ "$3" = "all" ] || [ "$3" = "" ]
		then

			# Purge Nginx PHP5 MySQL Postfix
			PURGEALL

			# Remove Unwanted Packages
			AUTOREMOVE
			REMOVEWPCLI
			REMOVEPMA

			# Display Success Message
			echo -e "\033[34mNginx PHP5 WP-CLI MySQL Postfix phpMyAdmin Successfully Purged\e[0m"

		fi

	else
		echo -e "\033[34mList Of Available Commands:\e[0m"
		echo -e "\tpurge:\t Purge Nginx PHP5-FPM phpMyAdmin MySQL And Postfix"
		echo -e "\tremove:\t Remove Nginx PHP5-FPM phpMyAdmin MySQL And Postfix"
		echo -e "\tinstall: Install Nginx PHP5-FPM phpMyAdmin MySQL And Postfix"

	fi


# Easy Engine Site Settings
elif [ "$1" = "site" ]
then

	# Easy Engine Site Enabled List
	if [ "$2" = "list" ]
	then

		if [ "$3" = "available" ]
		then

			# Display The List Of Available Sites
			echo -e "\033[34mDisplay The List Of Available Websites:\e[0m"
			ls /etc/nginx/sites-available/ \
			|| OwnError "Unable To Display The List Of Available Websites"

		else
		
			# Display The List Of Enabled Websites
			echo -e "\033[34mDisplay The List Of Enabled Websites:\e[0m"
			ls /etc/nginx/sites-enabled/ \
			|| OwnError "Unable To Display The List Of Enabled Websites"
		fi

	elif [ "$2" = "show" ]
	then

		# Check SITENAME Is Empty Or Not
		SITENAMECHECK=$3
		EESITENAME
		
		# Check The Website Is Exist
		ls /etc/nginx/sites-available/$DOMAIN &> /dev/null \
		|| OwnError "The $DOMAIN Is Not Found In Available Websites List"

		if [ $? -eq 0 ]
		then

			# Display The Specific Site Configuration
			echo -e "\033[34mDisplay Nginx Configuration For $DOMAIN\e[0m"
			cat /etc/nginx/sites-available/$DOMAIN \
			|| OwnError "Unable To Display Nginx Configuration For $DOMAIN"

		fi

	elif [ "$2" = "info" ]
	then

		# Check SITENAME Is Empty Or Not
		SITENAMECHECK=$3
		EESITENAME

		# Display The Specific Site Configuration
		EESITEINFO

	elif [ "$2" = "create" ]
	then

		# Configure Variables
		SITENAMECHECK=$3
		EESITECREATE=$4
		WPCACHEOPTION=$5

		# WordPress SubDirectory Variables
		if [ "$EESITECREATE" = "--wpsubdir" ] || [ "$EESITECREATE" = "--wpsubdirectory" ]
		then
			NETWORKACTIVATE="--network"
		fi

		# WordPress SubDomain Variables
		if [ "$EESITECREATE" = "--wpsubdom" ] || [ "$EESITECREATE" = "--wpsubdomain" ]
		then
			NETWORKACTIVATE="--network"
			WPSUBDOMAINS="--subdomains"
		fi

		# USE DEFAULT WHEN POSSIBLES
		# ee site create example.com
		if [ "$EESITECREATE" = "" ]
		then
			EESITECREATE=--html
		fi

		if [ "$EESITECREATE" = "--basic" ] || [ "$EESITECREATE" = "--w3tc" ] || [ "$EESITECREATE" = "--wpsc" ] || [ "$EESITECREATE" = "--wpfc" ]
		then
			EESITECREATE=--wp
			WPCACHEOPTION=$4
		fi

		# If No Cache Specified Use --basic As Default
		if [ "$WPCACHEOPTION" = "" ] && [ "$EESITECREATE" != "--html" ] && [ "$EESITECREATE" != "--php" ]
		then
			WPCACHEOPTION=--basic
		fi


		if [ "$EESITECREATE" = "--html" ]
		then

			# Configure Variable
			NGINXCONF=html/basic.conf
			echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

			# Setup HTML Nginx
			EESITENAME
			EEDOMAINSETUP
			PERMISSIONANDGIT

			# Display Success Message
			echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

		elif [ "$EESITECREATE" = "--php" ]
		then

			# Configure Variable
			NGINXCONF=php/basic.conf
			echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

			# Setup PHP Nginx
			EESITENAME
			EEDOMAINSETUP
			PERMISSIONANDGIT

			# Display Success Message
			echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

		elif [ "$EESITECREATE" = "--mysql" ]
		then

			# Configure Variable
			NGINXCONF=mysql/basic.conf
			echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

			# Setup PHP Nginx
			EESITENAME
			EEDOMAINSETUP
			PERMISSIONANDGIT

			# Call MYSQLINFO Function For MySQL Values
			MYSQLINFO
			EECREATEDATABASE

			# Add Database Information On ee-config.php
			echo -e "define('DB_NAME', '$WPDBNAME'); \ndefine('DB_USER', '$WPDBUSER'); \ndefine('DB_PASSWORD', '$WPDBPASS'); \ndefine('DB_HOST', '$MYSQLHOST');" \
			&>> /var/www/$DOMAIN/ee-config.php

			# Display Success Message
			echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

		elif [ "$EESITECREATE" = "--wp" ]
		then

			if [ "$WPCACHEOPTION" = "--basic" ]
			then

				# Configure Variable
				NGINXCONF=wp/basic.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Basic Nginx
				SETUPDOMAIN
				NGINXHELPER
				PERMISSIONANDGIT

				# Display Success Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--w3tc" ]
			then

				# Configure Variable
				NGINXCONF=wp/w3tc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup W3 Total Cache Nginx
				SETUPDOMAIN
				NGINXHELPER
				TOTALCACHENGINX
				PERMISSIONANDGIT

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mW3 Total Cache: http://$DOMAIN/wp-admin/admin.php?page=w3tc_general\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--wpsc" ]
			then

				# Configure Variable
				NGINXCONF=wp/wpsc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup WP Super Cache Nginx
				SETUPDOMAIN
				NGINXHELPER
				SUPERCACHENGINX
				PERMISSIONANDGIT

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mWP Super Cache: http://$DOMAIN/wp-admin/options-general.php?page=wpsupercache\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--wpfc" ]
			then

				# Configure Variable
				NGINXCONF=wp/wpfc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Fastcgi Cache Nginx
				SETUPDOMAIN
				NGINXHELPER
				TOTALCACHENGINX
				PERMISSIONANDGIT

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mNginx Helper: http://$DOMAIN/wp-admin/options-general.php?page=nginx\e[0m"
				echo -e "\033[34mW3 Total Cache: http://$DOMAIN/wp-admin/admin.php?page=w3tc_general\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			fi

		elif [ "$EESITECREATE" = "--wpsubdir" ] || [ "$EESITECREATE" = "--wpsubdirectory" ]
		then

			if [ "$WPCACHEOPTION" = "--basic" ]
			then

				# Configure Variable
				NGINXCONF=wpsubdir/basic.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Domain WordPress & Database
				SETUPDOMAIN
				
				# Setup WordPress SubDirectory Network
				SETUPWPNETWORK
				PERMISSIONANDGIT

				# Setup phpMyAdmin
				#ln -s /var/www/eeadmin/htdocs/db/pma /var/www/$DOMAIN/htdocs/pma

				# Display Success Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--w3tc" ]
			then

				# Configure Variable
				NGINXCONF=wpsubdir/w3tc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Domain WordPress & Database
				SETUPDOMAIN

				# Setup WordPress SubDirectory Network
				SETUPWPNETWORK
				TOTALCACHENGINX
				PERMISSIONANDGIT

				# Setup phpMyAdmin
				#ln -s /var/www/eeadmin/htdocs/db/pma /var/www/$DOMAIN/htdocs/pma

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mW3 Total Cache: http://$DOMAIN/wp-admin/network/admin.php?page=w3tc_general\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--wpsc" ]
			then

				# Configure Variable
				NGINXCONF=wpsubdir/wpsc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Domain WordPress & Database
				SETUPDOMAIN

				# Setup WordPress SubDirectory Network
				SETUPWPNETWORK
				SUPERCACHENGINX
				PERMISSIONANDGIT

				# Setup phpMyAdmin
				#ln -s /var/www/eeadmin/htdocs/db/pma /var/www/$DOMAIN/htdocs/pma

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mWP Super Cache: http://$DOMAIN/wp-admin/network/settings.php?page=wpsupercache\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--wpfc" ]
			then

				# Configure Variable
				NGINXCONF=wpsubdir/wpfc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Domain WordPress & Database
				SETUPDOMAIN

				# Setup WordPress SubDirectory Network
				SETUPWPNETWORK
				TOTALCACHENGINX
				PERMISSIONANDGIT

				# Setup phpMyAdmin
				#ln -s /var/www/eeadmin/htdocs/db/pma /var/www/$DOMAIN/htdocs/pma

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mNginx Helper: http://$DOMAIN/wp-admin/network/settings.php?page=nginx\e[0m"
				echo -e "\033[34mW3 Total Cache: http://$DOMAIN/wp-admin/network/admin.php?page=w3tc_general\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			fi

		elif [ "$EESITECREATE" = "--wpsubdom" ] || [ "$EESITECREATE" = "--wpsubdomain" ]
		then

			if [ "$WPCACHEOPTION" = "--basic" ]
			then

				# Configure Variable
				NGINXCONF=wpsubdomain/basic.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Domain WordPress & Database
				SETUPDOMAIN
				
				# Setup WordPress SubDirectory Network
				SETUPWPNETWORK
				PERMISSIONANDGIT

				# Setup phpMyAdmin
				#ln -s /var/www/eeadmin/htdocs/db/pma /var/www/$DOMAIN/htdocs/pma

				# Display Success Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--w3tc" ]
			then

				# Configure Variable
				NGINXCONF=wpsubdomain/w3tc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Domain WordPress & Database
				SETUPDOMAIN

				# Setup WordPress SubDirectory Network
				SETUPWPNETWORK
				TOTALCACHENGINX
				PERMISSIONANDGIT

				# Setup phpMyAdmin
				#ln -s /var/www/eeadmin/htdocs/db/pma /var/www/$DOMAIN/htdocs/pma

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mW3 Total Cache: http://$DOMAIN/wp-admin/network/admin.php?page=w3tc_general\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--wpsc" ]
			then

				# Configure Variable
				NGINXCONF=wpsubdomain/wpsc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Domain WordPress & Database
				SETUPDOMAIN

				# Setup WordPress SubDirectory Network
				SETUPWPNETWORK
				SUPERCACHENGINX
				PERMISSIONANDGIT

				# Setup phpMyAdmin
				#ln -s /var/www/eeadmin/htdocs/db/pma /var/www/$DOMAIN/htdocs/pma

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mWP Super Cache: http://$DOMAIN/wp-admin/network/settings.php?page=wpsupercache\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			elif [ "$WPCACHEOPTION" = "--wpfc" ]
			then

				# Configure Variable
				NGINXCONF=wpsubdomain/wpfc.conf
				echo -e "SITENAMECHECK = $SITENAMECHECK \nEESITECREATE = $EESITECREATE \nWPCACHEOPTION = $WPCACHEOPTION \nNETWORKACTIVATE = $NETWORKACTIVATE \nWPSUBDOMAINS = $WPSUBDOMAINS \nNGINXCONF = $NGINXCONF" &>> $INSTALLLOG

				# Setup Domain WordPress & Database
				SETUPDOMAIN

				# Setup WordPress SubDirectory Network
				SETUPWPNETWORK
				TOTALCACHENGINX
				PERMISSIONANDGIT

				# Setup phpMyAdmin
				#ln -s /var/www/eeadmin/htdocs/db/pma /var/www/$DOMAIN/htdocs/pma

				# Display WordPress Plugin Configuration Message
				echo
				echo -e "\033[37mWordPress Admin Username: $WPADMINUSER\e[0m"
				echo -e "\033[37mWordPress Admin Password: $WPADMINPASS\e[0m"
				echo
				echo -e "\033[34mPlease Configure The Following Settings...\e[0m"
				#echo -e "\033[34mPermalink Settings: http://$DOMAIN/wp-admin/options-permalink.php\e[0m"
				echo -e "\033[34mNginx Helper: http://$DOMAIN/wp-admin/network/settings.php?page=nginx\e[0m"
				echo -e "\033[34mW3 Total Cache: http://$DOMAIN/wp-admin/network/admin.php?page=w3tc_general\e[0m"

				# Display Success Message
				echo
				echo -e "\033[37mSuccessfully Created New Website: http://$WWWDOMAIN\e[0m"

			fi
		fi

	elif [ "$2" = "enable" ]
	then

		# Check SITENAME Is Empty Or Not
		SITENAMECHECK=$3
		EESITENAME

		# Creating Symbolic Link
		NGINXSYMBOLICLINK

		# Reload Nginx Configuration
		NGINXRELOAD

		# Take Nginx Configuration In Git Version Control
		EEGITDIR=/etc/nginx
		EEGITMESSAGE="Enable Website: $DOMAIN"
		EEGITCOMMIT

	elif [ "$2" = "disable" ]
	then

		# Check SITENAME Is Empty Or Not
		SITENAMECHECK=$3
		EESITENAME

		# Remove Symbolic Link
		echo -e "\033[34mRemoving Symbolic Link For $DOMAIN\e[0m"
		rm /etc/nginx/sites-enabled/$DOMAIN \
		|| OwnError "Unable To Remove Symbolic Link For $DOMAIN"

		# Reload Nginx Configuration
		NGINXRELOAD

		# Take Nginx Configuration In Git Version Control
		EEGITDIR=/etc/nginx
		EEGITMESSAGE="Disable Website: $DOMAIN"
		EEGITCOMMIT

	elif [ "$2" = "delete" ]
	then

		# Check SITENAME Is Empty Or Not
		SITENAMECHECK=$3
		SITEDELETEARG=$4
		EESITENAME

		# USE DEFAULT WHEN POSSIBLES
		if [ "$SITEDELETEARG" = "" ]
		then
			SITEDELETEARG=--all
		fi

		if [ "$SITEDELETEARG" = "--db" ]
		then

			# Remove Database
			REMOVEDB

		elif [ "$SITEDELETEARG" = "--files" ]
		then

			# Remove Webroot
			REMOVEFILES

		elif [ "$SITEDELETEARG" = "--all" ]
		then

			# Remove All Database And Webroot
			REMOVEDB
			REMOVEFILES

			# Remove Nginx Configuration
			REMOVENGINXCONF

			# Reload Nginx
			NGINXRELOAD

			# Take Nginx Configuration In Git Version Control
			EEGITDIR=/etc/nginx
			EEGITMESSAGE="Delete Website With $SITEDELETEARG Option: $DOMAIN"
			EEGITCOMMIT

		fi

	else
		echo -e "\033[34mList Of Available Commands:\e[0m"
		echo -e "\tinfo:\t Dispaly Information About Given Website"
		echo -e "\tlist:\t List Nginx Enabled Websites"
		echo -e "\tshow:\t Display Nginx Configuration For Given Website"
		echo -e "\tcreate:\t Create A New HTML PHP MySQL & WordPress Website"
		echo -e "\tdelete:\t Delete Existing Website"
		echo -e "\tenable:\t Enable Website"
		echo -e "\tdisable: Disable Website"
	fi


elif [ "$1" = "update" ]
then

	# Update EasyEngine
	echo -e "\033[34mChecking EasyEngine Update, Please Wait...\e[0m"
	/bin/bash <(curl -sL https://raw.github.com/rtCamp/easyengine/stable/usr/local/sbin/eeupdate)

else
	echo -e "\033[34mList Of Available Commands:\e[0m"
	echo -e "\tinfo:\t Display Nginx PHP MySQL Information\t"
	echo -e "\thelp:\t Display EasyEngine Help\t"
	echo -e "\tsite:\t Do Various Site Specific Operations\t"
	echo -e "\tsystem:\t Do Various System Level Operations\t"
	echo -e "\tupdate:\t Update EasyEngine (ee)\t"
	echo -e "\tversion: Display EasyEngine (ee) Version\t"


fi

}

EasyEngine $@ | tee -ai $INSTALLLOG
