#!/usr/bin/env bash

actual_checksum=$(curl http://ee.org/packages/phar/ee.phar | md5sum | cut -d ' ' -f 1)

echo "expected:" $(curl -s http://ee.org/packages/phar/ee.phar.md5)
echo "actual:  " $actual_checksum

actual_checksum=$(curl http://ee.org/packages/phar/ee.phar | sha512sum | cut -d ' ' -f 1)

echo "expected SHA-512:" $(curl -s http://ee.org/packages/phar/ee.phar.sha512)
echo "actual SHA-512:  " $actual_checksum
